server.port=${PORT:7070}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/travellog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB

file.upload-dir=${FILE_UPLOAD_DIR:C:/uploads/travellog/}
google.maps.key=${GOOGLE_MAPS_KEY:AIzaSyDb83VGHmkFRihjpbAGZF_Ij5-ee4l6SG0}

server.servlet.session.timeout=86400
server.servlet.session.cookie.http-only=true
server.servlet.session.tracking-modes=cookie

weather.api.key=${WEATHER_API_KEY:4cebee711f4243e9d82f3bd7d6a38e64}

logging.level.org.springframework.security=DEBUG