spring.application.name=travellog
server.port=${SERVER_PORT:7070}

# DB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/travellog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# 파일 업로드
file.upload-dir=${FILE_UPLOAD_DIR:C:/uploads/travellog/}

# API 키
google.maps.key=${GOOGLE_MAPS_KEY}
weather.api.key=${WEATHER_API_KEY:4cebee711f4243e9d82f3bd7d6a38e64}

# 파일 크기
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB